##################
##Website Config##
##################

url: "https://mmistakes.github.io" # the base hostname & protocol for your site http://localhost:4000
base_path: "" # the directory path on the website. e.g. /website

# Margin left&right of Website
maginLeftRight: "3"


# Name shown in browser tab
nameTab: "[EDIT_ME]"
nameFooter: "[EDIT_ME]"

# Navbar brand name
nameTitle: "[EDIT_ME]"
# Navbar image
navbarImgPath: "/favicon.png"
# Navbar color
colorNavbar: "#E6E6FA"
colorNavbarText: "black"

# Footer color
footerBackgroundColor: "#E6E6FA"

# Text separator that is used to delimitate which section of the post is displayed on main page
excerpt_separator: "\n\n"

##################
##Social Account##
##################
#/!\ Not displayed if not set
linkedInAccount: ""
instagramAccount: ""
githubAccount: ""
mailAccount: ""

############
##Carousel##
############
#First image (fill only that one if you want a banner)
firstImageLink: "https://cdn.pixabay.com/photo/2017/05/27/03/13/rollercoaster-2347515_1280.jpg"
firstImageHeadline: "Welcome on this website"
firstImageSubtitle: "Here you will discover different article on coaster"
firstLinkClick: "https://www.google.com"

#if you want a gliding carousel fill the second
secondImageLink: "https://cdn.pixabay.com/photo/2020/10/21/19/43/jack-o-lanterns-5674148_1280.jpg"
secondImageHeadline: "Halloween Article"
secondImageSubtitle: "Read the newest article"
secondLinkClick: ""

#you can even have a third image
thirdImageLink: "https://cdn.pixabay.com/photo/2016/05/24/16/48/mountains-1412683_1280.png"
thirdImageHeadline: ""
thirdImageSubtitle: ""
thirdLinkClick: ""