##################
##Website Config##
##################

# Name shown in browser tab
nameTab: "[EDIT_ME]"
nameFooter: "[EDIT_ME]"
nameTitle: "[EDIT_ME]"

# Navbar image
navbarImgPath: "favicon.png"

# Text separator that is used to delimitate which section of the post is displayed on main page
excerpt_separator: "\n\n"

##################
##Social Account##
##################
#/!\ Not displayed if not set
linkedInAccount: ""
instagramAccount: ""
githubAccount: ""
mailAccount: ""