# Continuous Integration Script inspired from https://github.com/jekyll/minima
name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: "Test with Jekyll ${{ matrix.jekyll }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        jekyll: ["~> 3.9", "~> 4.2"]
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: false
      - name: Run Bootstrap
        run: script/bootstrap
      - name: Run tests
        run: script/cibuild